apiVersion: v1
kind: Service
metadata:
  name: dummy-service-production
  namespace: default
spec:
  type: NodePort
  selector:
    app: dummy-service
    env: production
  ports:
  - port: 80 # Internal service port
    targetPort: 9000
    nodePort: 31123
    name: dummy-service-production
